#!/bin/bash
echo "==> Building the binary with params:"
echo "==> VERSION=$LOGSTASH_VERSION"
echo "==> VERSION=$LOGSTASH_VERSION"
echo "==> Image=$logstash-date-formatter:$LOGSTASH_VERSION"
echo "==> Dockerfile=$DOCKERFILE_PATH"
docker build --build-arg VERSION=$LOGSTASH_VERSION -f $DOCKERFILE_PATH -t $IMAGE_NAME