#!/bin/bash
echo "=> Building the binary with params: VERSION=$LOGSTASH_VERSION Image=$IMAGE_NAME Dockerfile=$DOCKERFILE_PATH"
docker build --build-arg VERSION=$LOGSTASH_VERSION -f $DOCKERFILE_PATH -t $IMAGE_NAME